- name: WebPerformance
  excerpt: "Fussgängerzone oder Autobahn?"
  url: /trainings/webperformance.html
  duration: 1
  trainings:
    - date: 2015-08-19
      location: Berlin
  tags:
    - WebPerf

- name: Ruby on Rails 4.2 und 5.0
  excerpt: "Ruby on Rails 4.2 und 5.0 Training"
  url: /trainings/ruby-on-rails.html
  duration: 2
  trainings:
    - date: 2015-08-17
      location: Berlin
  tags:
    - Rails
