- name: WebPerformance
  excerpt: "Fussgängerzone oder Autobahn?"
  url: /trainings/webperformance.html
  duration: 1
  trainings:
    - date: 2015-12-02
      location: Berlin
    - date: 2015-12-16
      location: Köln
    - date: 2016-01-20
      location: München
  price: 885
  tags:
    - WebPerf

- name: Ruby on Rails 4.2 und 5.0
  excerpt: "Ruby on Rails 4.2 und 5.0 Training"
  url: /trainings/ruby-on-rails.html
  duration: 2
  trainings:
    - date: 2015-11-30
      location: Berlin
    - date: 2015-12-14
      location: Köln
    - date: 2016-01-18
      location: München
  price: 975
  tags:
    - Rails
